CC = c++

CFLAGS = -Wall -Werror -Wextra -std=c++98

NAME = fixed

SRC =	main.cpp \
		Fixed.cpp

OBJ = $(SRC:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJ)
		$(CC) $(CFLAGS) $(OBJ) -o $@
	
clean: 
		rm -f $(OBJ)

fclean: clean
		rm -f $(NAME)

re: fclean re

.PHONY: all clean fclean re